### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by muguiping** [tg123/wowtip.js#1]
你好，新浪云的数据已经无法访问，我把源码下载到本地，运行时报错，请问你还提供版本更新吗？谢谢。
Warning: include(index.markdown.php): failed to open stream: No such file or directory in D:\phpStudy\PHPTutorial\WWW\wowtip\index.php on line 17
Warning: include(): Failed opening 'index.markdown.php' for inclusion (include_path='.;C:\php\pear') in D:\phpStudy\PHPTutorial\WWW\wowtip\index.php on line 17

**Comment by tg123** [comment]
这个文件可以忽略不影响使用

**Comment by muguiping** [comment]
我把这个文件安装到了https://2b.gg/wowtip
页面能够打开，但是只能看到一个链接到http://sae.sina.com.cn/的新浪云图标，您能看看是什么原因吗？谢谢

**Comment by muguiping** [comment]
在很多年前，你在NGACN发布了一个用于显示魔兽世界装备提示的程序，当时我也下载并运行成功了的。我印象中那个程序附带了很多数据包，每一个数据包都是一件装备的属性内容。
我现在的BLOG是用来记录自己在魔兽世界中的点滴，有些文章需要直接将装备以属性标签的形式展现，需要展示的文章比较少，不需要在主机中安装完整的魔兽世界装备库数据，如果能使用你之前发布的这个程序是最方便的。
但是因为时间太过久远，之前在NGACN下载的文件包已经找不到了。我也尝试在NGA搜索旧帖子，希望能在你当年发表的文章中下载附件。我还尝试过用这个程序的名字在所有搜索引擎搜寻，看能不能找到一些蛛丝马迹或者哪位网友的存档文件，结果一无所获。
实在没有办法的情况下，找到这里来向你寻求帮助。你当年写的程序还有备份文件吗？能不能给我一份？
谢谢。

**Comment by tg123** [comment]
应该有备份的
这个版本 居然没放数据……
我 稍后找下

**Comment by muguiping** [comment]
老哥，请问找到备份文件了吗？如果找到的话，麻烦给我一份，谢谢。

**Comment by tg123** [comment]
我 在古代硬盘上找到了 Google 有备份哈哈
https://code.google.com/archive/p/itemstatlite/downloads

**Comment by muguiping** [comment]
谢谢谢谢！
老哥啊，Google上面存储的貌似不是我需求的那个版本啊。。。
我需要的是“程序附带了很多数据文件，每一个数据文件都是一件装备的属性内容。”，可以自己任意修改每件装备的属性。
并非引用其他网站的数据！！！
我之前还用这个版本做过一些奇怪属性的，比如下面这个：

https://2b.gg/wp-content/uploads/2018/04/mssjnbxrsd7dsp01.jpg

https://2b.gg/wp-content/uploads/2018/04/mssjnbxrsd7dsp02.jpg

https://2b.gg/wp-content/uploads/2018/04/mssjnbxrsd7dsp03.jpg

https://2b.gg/wp-content/uploads/2018/04/mssjnbxrsd7dsp04.jpg

https://2b.gg/wp-content/uploads/2018/04/mssjnbxrsd7dsp05.jpg

https://2b.gg/wp-content/uploads/2018/04/mssjnbxrsd7dsp06.jpg

https://2b.gg/wp-content/uploads/2018/04/mssjnbxrsd7dsp07.jpg

再次麻烦您看看，这个版本的文件还有备份吗？谢谢！




前不久我在QQ上和你联系的时候其实就把你在Google储存的版本全部下载来尝试过了，都不是我描述的版本。
我刚才把google上面的文件全部下载到电脑看了一下，确实都不是我需要的那个版本，可能是我没有描述清楚。
那个版本的所有装备数据都是在网站储存的，好像全部都是以数字命名的，每一件装备数据都是一个独立的文件，我大概记得数据文件打开之后，里面就是一件装备的名称、等级、主要属性、附加属性、字体颜色等等之类的信息。
希望我这些凌乱的记忆描述能够说清楚我需求的那个版本的特征。
再次感谢！
